//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGMTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGS
    {
        public int LOG_ID { get; set; }
        public Nullable<bool> LOG_ERROR { get; set; }
        public string LOG_MENSAJE { get; set; }
        public System.DateTime LOG_FECHA { get; set; }
        public string LOG_CAMPO_AUX1 { get; set; }
        public string LOG_CAMPO_AUX2 { get; set; }
        public string LOG_CAMPO_AUX3 { get; set; }
    }
}
