//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGMTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.HISTORICO_LOGIN = new HashSet<HISTORICO_LOGIN>();
        }
    
        public int USU_ID { get; set; }

        public string USU_NOMBRE { get; set; }

        public string USU_CORREO { get; set; }

        public string USU_CONTRA { get; set; }
        public Nullable<bool> USU_ACTIVO { get; set; }
        public System.DateTime USU_FECHA_CREACION { get; set; }
        public string USU_SALT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORICO_LOGIN> HISTORICO_LOGIN { get; set; }
    }
}
